name: CI

on:
  pull_request:
    paths:
      - "**.js"
      - "**eslint**"
      - "package.json"
      - ".github/workflows/lint.yml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - run: npm install
      - run: npm run lint
